### PR TITLE
Bump Cake to 1.0.0

### LINKED ISSUE #101: Build against Cake 1.0
Build against Cake 1.0

### PR DESCRIPTION
**Pull request by mhoellner**
* Update to Cake.Core 1.0.0

Fixes #101

### CODE REVIEW

**Comment by mhoellner** [comment]
I suppose we need to wait for Cake.Recipe to support Cake 1.0.0 for a successful build (https://github.com/cake-contrib/Cake.Recipe/pull/799).

**Review by pascalberger — CHANGES_REQUESTED** [review]
> I suppose we need to wait for Cake.Recipe to support Cake 1.0.0 for a successful build ([cake-contrib/Cake.Recipe#799](https://github.com/cake-contrib/Cake.Recipe/pull/799)).

Thanks for the PR 👍 There's no need to build with Cake 1.0, we can just bump the Cake version in the project (and keep the version in the `packages.config`. Also the change in the AppVeyor.yml file should not be required, as the changed target would require Cake.Recipe 2.x.

**Comment by pascalberger** [comment]
Sorry, AppVeyor image needs to be updated to Visual Studio 2019 to have .NET 5 available

**Comment by mhoellner** [comment]
The build is still failing. Is this due to the slack integration?

**Comment by mhoellner** [comment]
Hey @pascalberger, what can I do to get this merged? Is the CI build only failing due to the slack integration?

**Comment by pascalberger** [comment]
@mhoellner your changes have been merged, thanks for your contribution 👍

**Pull request merged**
