### PR TITLE
(GH-84) Add support of --warningsAsErrors build parameter

### LINKED ISSUE #84: Add support of --warningsAsErrors parameter to build command
Add support of `--warningsAsErrors` parameter to `build` command

### PR DESCRIPTION
**Pull request by bgiot**
Add the support of --warningsAsErrors build parameter to CI cake build can fail if we have warnings 

Fixes #84

### CODE REVIEW

**Comment by bgiot** [comment]
Note that Docfx CLI commands (build, server, merge, ...) have a common set of parameters. See [LogOptions.cs] (https://github.com/dotnet/docfx/blob/dev/src/docfx/Models/LogOptions.cs)
Maybe general support of those parameters would be nice...

**Comment by pascalberger** [comment]
@bgiot your changes have been merged, thanks for your contribution 👍

You're right about the common parameters. Are you interested to create a PR for this?

**Comment by bgiot** [comment]
I'll do the PR for supporting all the common parameters, for sure!
In the meantime, whould it be possible to already release a new version with the PR you merged ? We really need that --warningsAsErrors parameter ... thanks!

**Comment by pascalberger** [comment]
@bgiot I'll create a release later today. In the meantime you can get the latest version from MyGet [here](https://myget.org/feed/cake-contrib/package/nuget/Cake.DocFx).

**Comment by pascalberger** [comment]
@bgiot Version 0.11.0 containing this improvement is available now on NuGet

**Pull request merged**
